### PR TITLE
Docsify-Based Documentation to ./docs Directory

### LINKED ISSUE #3: Proposed Documentation Site Enhancement for Barnsley-Fractal
### Description

I'd like to propose enhancing the Barnsley-Fractal repository with an improved documentation site using Docsify. Docsify is a lightweight and flexible documentation generator that makes it easy to create beautiful, organized, and user-friendly documentation websites.

### Motivation

Good documentation is essential for both users and contributors to the Barnsley-Fractal project. Docsify can help us create a more engaging and user-friendly documentation site, which will ultimately improve the experience for everyone.

### Suggested Changes

I suggest the following changes as part of this enhancement:
1. Setting up Docsify in a designated folder within the Barnsley-Fractal repository.
2. Creating and structuring documentation content to match Barnsley-Fractal's needs.
3. Configuring Docsify's settings, themes, and plugins to provide a seamless experience.

### Implementation Steps

To achieve this, here are the proposed implementation steps:
1. Create a new branch for the documentation site: `git checkout -b docsify-enhancement`
2. Set up Docsify within the Barnsley-Fractal repository.
3. Add content to the documentation site.
4. Configure Docsify according to Barnsley-Fractal's needs.
5. Test the documentation site to ensure it works as expected.
6. Make a pull request with the changes and seek feedback from the community.

### Hosting 
It would be ideal if the documentation site could be hosted through GitHub Pages for easy access.

### Additional Information

If there are specific details, suggestions, or ideas for the documentation site, please provide them here. Feel free to discuss and share your thoughts on this enhancement.

### Related Issues

If there are any related issues, please link them here for context.

### Assignees

Assign this issue to any relevant contributors if you have someone in mind.

### Labels

Consider labeling this issue with tags like "documentation," "enhancement," and "Docsify" for easier tracking and organization.

Thank you for considering this proposal, and let's work together to enhance Barnsley-Fractal's documentation!

### PR DESCRIPTION
**Pull request by codebyrpp**
### Description

This pull request adds Docsify-based documentation to the `./docs` directory in the Barnsley-Fractal repository. Additionally, it relocates the README file to this folder to serve as the landing page for the documentation site.

### Changes Made

The following changes have been made in this PR:

1. Initialized Docsify in the `./docs` directory.
2. Moved the README file to the `./docs` directory for use as the landing page.
3. Structured and organized documentation content within the `./docs` directory.

### Implementation Details

To achieve this, I followed these implementation steps:

1. Initialized Docsify in the `./docs` directory to set up the documentation framework.
2. Moved the README file to the `./docs` directory.
3. Structured the documentation content as required.
4. Configured Docsify settings, themes, and plugins for an improved user experience.
5. Tested the documentation site to ensure it works as expected.

To locally test the implemented changes,
1. Install docsify 
```bash
npm i docsify-cli -g
```
2. Run the local server with docsify serve. You can preview your site in your browser on `http://localhost:3000`.
```bash
docsify serve docs
```

### Related Issues

This PR is related to #3 , which proposed enhancing the documentation for Barnsley-Fractal using Docsify.

### Screenshots

image

### Deployment

GitHub Pages can be used to deploy the documentation easily once this PR is merged.
Please follow these [steps mentioned in the docsify documentation](https://docsify.js.org/#/deploy?id=github-pages).

### Labels

Consider labeling this PR with tags like "documentation," "enhancement," and "Docsify" for easier tracking and organization.

### CODE REVIEW

**Comment by chathura-de-silva** [comment]
@rajivaPavan What is that `.hintrc` thing in the root.   By the way I have invited you to be a collaborator.

**Review by chathura-de-silva — APPROVED** [review]
1. What is that `.hintrc` thing in the root.   
2. @rajivaPavan Is it necessary to change this : 
  ```markdown
  1.  [Getting Started](#getting-started)
  2.  [Feature configuration](#feature-configuration)
      * [Using the Commandline for basic preferences](#using-the-commandline)
      * [Through `preferences_barnsley.json`](#creatingediting-the-preferences_barnsleyjson)
  3.  [What is Barnsley Fractal?](#what-is-barnsley-fractal)
      * [Mathematical Foundations](#mathematical-foundations)
      * [Visual Charasteristics](#visual-characteristics)
      * [Applications](#applications)
  4.  [For what?](#for-what)
  5.  [Gallery](#gallery) 
  6.  [Contributions](#contributions)
  ```
  
  To this : 
  ```markdown
  - [Barnsley Fractal](#barnsley-fractal)
    - [Features](#features)
    - [Quick Links](#quick-links)
    - [Getting Started](#getting-started)
    - [Feature Configuration](#feature-configuration)
      - [Using the Commandline](#using-the-commandline)
      - [Creating/Editing the `preferences_barnsley.json`.](#creatingediting-the-preferences_barnsleyjson)
    - [What is Barnsley Fractal?](#what-is-barnsley-fractal)
      - [Mathematical Foundations](#mathematical-foundations)
      - [Visual Characteristics](#visual-characteristics)
      - [Applications](#applications)
    - [For What?](#for-what)
    - [Gallery](#gallery)
    - [Contributions](#contributions)
  ```
  
  If it is, then merge. Otherwise rollback them and merge. ( By the way I have invited you to be a collaborator. )

**Comment by codebyrpp** [comment]
My bad, I'll remove the hintrc file.

**Comment by codebyrpp** [comment]
@chathura-de-silva as for the change in the quick links section, for some reason my code editor (used vscode) recognizes it as a table of contents which is out of date. When I save the file, it automatically updates it. Thats why that change had been made. I made the changes as requested.

**Review by chathura-de-silva — APPROVED** [review]

**Pull request merged**
